use crate::{
    controllers::{
        account, admin, announcement, artist, auth, backup, band, band_note, billing, gig, metrics,
        migrations, moderation, notification, pin, public, release_note, setlist, song, status,
        suggestion, tour, trash, user,
    },
    export::pdf::{ChordMode, MarginSize, Orientation, PaperFormat, PdfLocale},
    models::{
        admin::{
            AdminBandDetail, AdminBandSummary, AdminSetlistDetail, AdminSetlistSummary,
            AdminSongDetail, AdminSongSummary, AdminTransferOwnershipPayload,
            AdminUpdateBandMemberRolePayload, AdminUserBand, AdminUserOverview, RevokeSharePayload,
            SharedLink,
        },
        announcement::{
            ActiveAnnouncements, AdminAnnouncement, Announcement, AnnouncementLevel,
            AnnouncementReceipt, AnnouncementStats, AnnouncementStatus, AudiencePayload,
            AudiencePreview, CreateAnnouncementPayload, UpdateAnnouncementPayload,
            UserAnnouncement,
        },
        artist::Artist,
        audit::AuditLogEntry,
        auth::{
            ForgotPasswordPayload, GoogleSignInPayload, LoginOutcome, LoginPayload,
            LoginTwoFactorPayload, ReauthRequiredResponse, ResetPasswordPayload,
            TwoFactorChallengeResponse,
        },
        auth::{ImpersonationResponse, LoginResponse},
        backup::{BackupFile, BackupTour, ImportSummary},
        band::{
            AdminAddBandMemberPayload, Band, BandInvite, BandMember, BandPermission,
            BandRolePermission, BandRolePermissionEntry, BandWithMembership, MyBandPermissions,
            UpdateBandMemberTitlePayload, UpdateBandRolePermissionsPayload,
        },
        band_note::{
            BandNote, BandNoteAuthor, BandNoteColor, CreateBandNotePayload, UpdateBandNotePayload,
        },
        billing::{
            AdjustCreditsPayload, AdminSubscriptionView, BillingInterval, BillingMe,
            BillingOverview, BillingSettings, CheckoutPayload, CreatePromoCodePayload,
            CreatePromotionPayload, CreditEntry, CreditsSummary, GrantSubscriptionPayload,
            GrantTrialsPayload, GrantTrialsResponse, Plan, PlanPromotion, PromoCode, PromoKind,
            PromoRedemption, Promotion, PublicPlan, RedeemCodePayload, RedeemResponse,
            RedeemRewardPayload, RedemptionSummary, RedirectResponse, ReferralEntry,
            ReferralSettings, ReferralStatus, ReferralSummary, Reward, Subscription,
            SubscriptionEvent, SubscriptionSource, SubscriptionStatus, UpdatePromoCodePayload,
            UpdatePromotionPayload, UpsertPlanPayload,
        },
        communication::{
            Category, CategoryPrefs, ChannelPrefs, CommunicationSettings, UnsubscribeInfo,
            UnsubscribePayload, UpdateCommunicationPayload,
        },
        gig::{Gig, GigStatus, PublicGig},
        link::{Link, LinkInput, LinkProvider, Links},
        metrics::{
            AdminMetrics, AdminTimeseries, ArtistSongCount, GenreCount, MetricsResponse, RoleCount,
            TimeseriesPoint, TimeseriesResponse, UserMetrics, UserTimeseries,
        },
        moderation::{
            FlagBand, FlagUser, ModerationFlag, ModerationSource, ModerationStatus,
            ModerationSummary, ModerationTarget, RescanResponse, ResolveAction, ResolveFlagPayload,
        },
        notification::{Notification, NotificationType, UnreadCountResponse},
        pin::{PinItemType, PinRef, PinnedItem, ReorderPinsPayload},
        quota::{
            QuotaLimits, QuotaOverrides, QuotaReport, QuotaResource, QuotaUsageItem,
            UpdateUserQuotaPayload, UserQuotaSettings,
        },
        release_note::{
            CreateReleaseNotePayload, PublishReleaseNotePayload, ReleaseNote, ReleaseNoteItem,
            UpdateReleaseNotePayload,
        },
        security::{
            CodeSentResponse, EmailChangePayload, EmailCodePayload, LinkedIdentity,
            PasswordConfirmationPayload, RecoveryCodesResponse, SecurityOverview,
            TwoFactorCodePayload, TwoFactorDisablePayload, TwoFactorSetupResponse,
        },
        setlist::{
            DuplicateSetlistResponse, PublicMarker, PublicSetlist, Setlist, SetlistItem,
            SetlistMarker,
        },
        song::{
            Genre, PublicSong, RenameTagPayload, Song, SongSetlistRef, SongWithArtist, TagCount,
            Tonality,
        },
        status::PublicStatus,
        status::{ServiceHealth, Status},
        suggestion::{
            CreateSuggestionPayload, ResolveSuggestionPayload, Suggestion, SuggestionFilter,
            SuggestionSetlist, SuggestionSong, SuggestionStatus, SuggestionUser, SuggestionVotes,
            VotePayload,
        },
        tour::{
            CreateTourPayload, GigSummary, Tour, TourDetail, TourGigSetlist, TourStats,
            TourStatusFilter, UpdateTourPayload,
        },
        trash::{EmptyTrashResponse, TrashItem, TrashScope, TrashType},
        user::{
            AcceptTermsPayload, BandInCommon, DeleteAccountPayload, RegisterPayload, ReportReason,
            ReportUserPayload, UpdateCurrentUserPayload,
        },
        user::{
            AdminResetPasswordPayload, BanUserPayload, ChangePasswordPayload,
            ChangePasswordResponse, UserProfileView, UserPublic, UsernameAvailability,
            UsernameHistoryEntry,
        },
        user_preferences::{UpdatePreferencesPayload, UserPreferences},
    },
    services::entitlements::Feature,
};
use serde::Serialize;
use utoipa::{
    Modify,
    openapi::{
        self,
        security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
    },
};

#[derive(utoipa::OpenApi)]
#[openapi(
    info(
        title = "Setlyst API",
        description = "REST API for Setlyst — setlists, songs, bands and gigs for live musicians.",
        contact(name = "Allan Somensi", email = "allansomensidev@proton.me"),
        license(name = "MIT", identifier = "MIT")
    ),
    servers(
        (url = "/", description = "Default Server")
    ),
    modifiers(&AuthToken),
    paths(
        // Status
        status::show_status,
        status::show_status_details,

        // Public
        public::legal_version,
        public::list_plans,
        public::list_release_notes,
        public::inspect_unsubscribe,
        public::unsubscribe,

        // Migrations
        migrations::live_run,

        // Auth
        auth::login,
        auth::login_two_factor,
        auth::register,
        auth::verify,
        auth::forgot_password,
        auth::reset_password,
        auth::google_sign_in,

        // Account (self-service security)
        account::get_security,
        account::revoke_my_sessions,
        account::send_email_verification,
        account::verify_email,
        account::start_email_change,
        account::confirm_email_change,
        account::setup_two_factor,
        account::enable_two_factor,
        account::disable_two_factor,
        account::regenerate_recovery_codes,
        account::list_identities,
        account::unlink_identity,
        account::get_communication,
        account::update_communication,
        account::accept_terms,
        account::delete_current_user,

        // Users
        user::find_user_by_id,
        user::find_all_users,
        user::create_user,
        user::update_user,
        user::delete_user,
        user::get_current_user,
        user::update_current_user,
        user::change_current_user_password,
        user::check_username_availability,
        user::get_username_history,
        user::get_user_profile,
        user::get_current_user_preferences,
        user::update_current_user_preferences,
        user::get_user_preferences_by_id,
        user::get_user_overview,
        user::ban_user,
        user::unban_user,
        user::reset_user_password,
        user::revoke_user_sessions,
        user::impersonate_user,
        user::get_user_quotas,
        user::update_user_quotas,
        user::get_current_user_quotas,
        user::report_user,

        // Artists
        artist::find_artist_by_id,
        artist::find_all_artists,
        artist::create_artist,
        artist::update_artist,
        artist::delete_artist,

        // Songs
        song::find_song_by_id,
        song::find_song_setlists,
        song::find_all_songs,
        song::create_song,
        song::update_song,
        song::delete_song,
        song::export_songs_chordpro,
        song::list_song_tags,
        song::rename_song_tag,
        song::delete_song_tag,
        song::export_song_pdf,
        song::export_song_chordpro,
        song::import_chordpro,

        // Setlists
        setlist::find_setlist_by_id,
        setlist::find_all_setlists,
        setlist::create_setlist,
        setlist::update_setlist,
        setlist::delete_setlist,
        setlist::add_song_to_setlist,
        setlist::remove_song_from_setlist,
        setlist::get_setlist_songs,
        setlist::reorder_setlist_songs,
        setlist::duplicate_setlist,
        setlist::get_setlist_items,
        setlist::reorder_setlist_items,
        setlist::create_setlist_block,
        setlist::update_setlist_block,
        setlist::create_setlist_break,
        setlist::update_setlist_break,
        setlist::delete_setlist_marker,
        setlist::export_setlist_pdf,
        setlist::enable_setlist_sharing,
        setlist::disable_setlist_sharing,
        setlist::favorite_setlist,
        setlist::unfavorite_setlist,
        setlist::get_public_setlist,
        setlist::export_public_setlist_pdf,

        // Gigs
        gig::find_gig_by_id,
        gig::find_all_gigs,
        gig::create_gig,
        gig::update_gig,
        gig::delete_gig,
        gig::enable_gig_sharing,
        gig::disable_gig_sharing,
        gig::get_public_gig,

        // Bands
        band::find_all_bands,
        band::find_band_by_id,
        band::create_band,
        band::update_band,
        band::delete_band,
        band::favorite_band,
        band::unfavorite_band,
        band::transfer_ownership,
        band::list_band_members,
        band::update_band_member_role,
        band::update_band_member_title,
        band::remove_band_member,
        band::create_band_invite,
        band::list_band_invites,
        band::revoke_band_invite,
        band::accept_band_invite,
        band::get_band_role_permissions,
        band::update_band_role_permissions,
        setlist::find_band_setlists,
        setlist::find_band_repertoire,
        gig::find_band_gigs,
        suggestion::list_suggestions,
        suggestion::create_suggestion,
        suggestion::vote_suggestion,
        suggestion::unvote_suggestion,
        suggestion::accept_suggestion,
        suggestion::reject_suggestion,
        suggestion::withdraw_suggestion,
        band_note::list_notes,
        band_note::create_note,
        band_note::update_note,
        band_note::delete_note,

        // Tours
        tour::find_all_tours,
        tour::find_band_tours,
        tour::create_tour,
        tour::find_tour_by_id,
        tour::update_tour,
        tour::delete_tour,

        // Trash
        trash::list_trash,
        trash::restore_item,
        trash::delete_item,
        trash::empty_trash,

        // Pins
        pin::list_pins,
        pin::pin_item,
        pin::unpin_item,
        pin::reorder_pins,

        // Metrics
        metrics::get_metrics,
        metrics::get_timeseries_metrics,

        // Notifications
        notification::list_notifications,
        notification::get_unread_count,
        notification::mark_notification_read,
        notification::mark_all_notifications_read,
        notification::delete_notification,

        // Backup
        backup::export_backup,
        backup::import_backup,

        // Admin
        admin::list_bands,
        admin::get_band,
        admin::update_band,
        admin::delete_band,
        admin::add_band_member,
        admin::update_band_member_role,
        admin::remove_band_member,
        admin::transfer_band_ownership,
        admin::list_songs,
        admin::get_song,
        admin::update_song,
        admin::delete_song,
        admin::list_setlists,
        admin::get_setlist,
        admin::update_setlist,
        admin::delete_setlist,
        admin::list_shared_links,
        admin::revoke_setlist_share,
        admin::unlock_setlist_share,
        admin::revoke_gig_share,
        admin::unlock_gig_share,
        admin::list_audit_logs,
        admin::get_quota_defaults,
        admin::update_quota_defaults,

        // Announcements
        announcement::admin_list,
        announcement::admin_create,
        announcement::admin_get,
        announcement::admin_update,
        announcement::admin_delete,
        announcement::admin_publish,
        announcement::admin_archive,
        announcement::admin_preview_audience,
        announcement::list_for_user,
        announcement::active_for_user,
        announcement::mark_seen,
        announcement::dismiss,
        announcement::acknowledge,

        // Release notes
        release_note::admin_list,
        release_note::admin_get,
        release_note::admin_create,
        release_note::admin_update,
        release_note::admin_delete,
        release_note::admin_publish,
        release_note::admin_unpublish,

        // Billing
        billing::get_me,
        billing::redeem_code,
        billing::list_credits,
        billing::redeem_reward,
        billing::list_referrals,
        billing::history,
        billing::checkout,
        billing::change_subscription,
        billing::portal,
        billing::stripe_webhook,
        billing::get_settings,
        billing::update_settings,
        billing::overview,
        billing::grant_trials,
        billing::list_plans,
        billing::get_plan,
        billing::upsert_plan,
        billing::get_user_subscription,
        billing::grant_user_subscription,
        billing::revoke_user_subscription,
        billing::adjust_user_credits,
        billing::list_promo_codes,
        billing::create_promo_code,
        billing::update_promo_code,
        billing::promo_redemptions,
        billing::list_promotions,
        billing::create_promotion,
        billing::update_promotion,
        billing::delete_promotion,

        // Moderation
        moderation::list_flags,
        moderation::summary,
        moderation::resolve_flag,
        moderation::rescan,
    ),
    components(
        schemas(
            Status,
            ServiceHealth,
            UserPublic,
            UserProfileView,
            AdminResetPasswordPayload,
            BanUserPayload,
            ChangePasswordResponse,
            UpdatePreferencesPayload,
            ImpersonationResponse,
            QuotaLimits,
            QuotaOverrides,
            QuotaReport,
            QuotaResource,
            QuotaUsageItem,
            UpdateUserQuotaPayload,
            UserQuotaSettings,
            AuditLogEntry,
            AdminAddBandMemberPayload,
            AdminBandDetail,
            AdminBandSummary,
            AdminSetlistDetail,
            AdminSongDetail,
            AdminSetlistSummary,
            AdminSongSummary,
            AdminTransferOwnershipPayload,
            AdminUpdateBandMemberRolePayload,
            AdminUserBand,
            AdminUserOverview,
            RevokeSharePayload,
            SharedLink,
            TagCount,
            RenameTagPayload,
            ChordMode,
            PaperFormat,
            Orientation,
            MarginSize,
            UsernameAvailability,
            UsernameHistoryEntry,
            ChangePasswordPayload,
            UserPreferences,
            Artist,
            Song,
            SongWithArtist,
            SongSetlistRef,
            Setlist,
            PublicSetlist,
            PublicSong,
            PublicMarker,
            DuplicateSetlistResponse,
            Link,
            LinkInput,
            LinkProvider,
            Links,
            Tour,
            TourDetail,
            TourGigSetlist,
            TourStats,
            TourStatusFilter,
            GigSummary,
            CreateTourPayload,
            UpdateTourPayload,
            TrashItem,
            TrashType,
            TrashScope,
            EmptyTrashResponse,
            Suggestion,
            SuggestionSetlist,
            SuggestionSong,
            SuggestionUser,
            SuggestionVotes,
            SuggestionStatus,
            SuggestionFilter,
            CreateSuggestionPayload,
            ResolveSuggestionPayload,
            VotePayload,
            BandNote,
            BandNoteAuthor,
            BandNoteColor,
            CreateBandNotePayload,
            UpdateBandNotePayload,
            PinnedItem,
            PinItemType,
            PinRef,
            ReorderPinsPayload,
            BackupTour,
            song::ImportChordProPayload,
            song::ChordProPreview,
            crate::import::chordpro::ImportWarning,
            SetlistMarker,
            SetlistItem,
            Gig,
            GigStatus,
            PublicGig,
            Tonality,
            Genre,
            Band,
            BandWithMembership,
            BandMember,
            BandInvite,
            BandPermission,
            BandRolePermission,
            BandRolePermissionEntry,
            MyBandPermissions,
            UpdateBandRolePermissionsPayload,
            UpdateBandMemberTitlePayload,
            MetricsResponse,
            UserMetrics,
            AdminMetrics,
            TimeseriesResponse,
            UserTimeseries,
            AdminTimeseries,
            TimeseriesPoint,
            GenreCount,
            ArtistSongCount,
            RoleCount,
            BackupFile,
            ImportSummary,
            PdfLocale,
            LoginResponse,
            LoginPayload,
            LoginOutcome,
            TwoFactorChallengeResponse,
            LoginTwoFactorPayload,
            ForgotPasswordPayload,
            ResetPasswordPayload,
            ReauthRequiredResponse,
            GoogleSignInPayload,
            RegisterPayload,
            UpdateCurrentUserPayload,
            AcceptTermsPayload,
            DeleteAccountPayload,
            ReportReason,
            ReportUserPayload,
            BandInCommon,
            PublicStatus,
            CodeSentResponse,
            EmailCodePayload,
            EmailChangePayload,
            SecurityOverview,
            PasswordConfirmationPayload,
            TwoFactorSetupResponse,
            TwoFactorCodePayload,
            TwoFactorDisablePayload,
            RecoveryCodesResponse,
            LinkedIdentity,
            Category,
            ChannelPrefs,
            CategoryPrefs,
            CommunicationSettings,
            UpdateCommunicationPayload,
            UnsubscribePayload,
            UnsubscribeInfo,
            Announcement,
            AnnouncementLevel,
            AnnouncementStatus,
            AnnouncementStats,
            AnnouncementReceipt,
            AdminAnnouncement,
            UserAnnouncement,
            ActiveAnnouncements,
            AudiencePayload,
            AudiencePreview,
            CreateAnnouncementPayload,
            UpdateAnnouncementPayload,
            ReleaseNote,
            ReleaseNoteItem,
            CreateReleaseNotePayload,
            UpdateReleaseNotePayload,
            PublishReleaseNotePayload,
            Feature,
            BillingSettings,
            ReferralSettings,
            Reward,
            Plan,
            PlanPromotion,
            PublicPlan,
            UpsertPlanPayload,
            Subscription,
            SubscriptionStatus,
            SubscriptionSource,
            SubscriptionEvent,
            BillingMe,
            BillingInterval,
            CheckoutPayload,
            RedirectResponse,
            CreditsSummary,
            ReferralSummary,
            RedeemCodePayload,
            RedeemResponse,
            RedemptionSummary,
            PromoKind,
            CreditEntry,
            RedeemRewardPayload,
            ReferralStatus,
            ReferralEntry,
            AdminSubscriptionView,
            GrantSubscriptionPayload,
            AdjustCreditsPayload,
            PromoCode,
            CreatePromoCodePayload,
            UpdatePromoCodePayload,
            PromoRedemption,
            Promotion,
            CreatePromotionPayload,
            UpdatePromotionPayload,
            GrantTrialsPayload,
            GrantTrialsResponse,
            BillingOverview,
            ModerationTarget,
            ModerationStatus,
            ModerationSource,
            FlagUser,
            FlagBand,
            ModerationFlag,
            ModerationSummary,
            ResolveAction,
            ResolveFlagPayload,
            RescanResponse,
            Notification,
            NotificationType,
            UnreadCountResponse,
        )
    ),
    tags(
        (name = "Status",     description = "Status endpoints"),
        (name = "Migrations", description = "Migrations endpoints"),
        (name = "Auth",       description = "Auth endpoints"),
        (name = "Users",      description = "Users endpoints"),
        (name = "Artists",    description = "Artists endpoints"),
        (name = "Songs",      description = "Songs endpoints"),
        (name = "Setlists",   description = "Setlist endpoints"),
        (name = "Gigs",       description = "Gig (show) endpoints"),
        (name = "Bands",      description = "Band, membership and invite endpoints"),
        (name = "Metrics",    description = "Metrics endpoints"),
        (name = "Notifications", description = "In-app notification endpoints"),
        (name = "Backup",     description = "Backup and restore endpoints"),
        (name = "Tours",      description = "Tours: named runs of gigs"),
        (name = "Trash",      description = "Deleted songs, artists, setlists, gigs and tours, until they are restored or purged"),
        (name = "Admin",      description = "Staff console: moderation, cross-tenant content management, audit log and platform limits"),
        (name = "Public",     description = "Public endpoints: legal version, plans, release notes, e-mail unsubscribe"),
        (name = "Account",    description = "Self-service account security: e-mail, two-factor authentication, linked providers, communication preferences, consent, deletion"),
        (name = "Announcements", description = "Platform announcements (staff console and recipients)"),
        (name = "Release notes", description = "What's new (staff console)"),
        (name = "Billing",    description = "The caller's plan, credits, promo codes and referrals"),
        (name = "Billing admin", description = "Plans, subscriptions, promo codes and promotions (staff)"),
        (name = "Moderation", description = "Moderation queue for avatars, usernames and band logos"),
    )
)]
pub struct ApiDoc;

#[derive(Debug, Serialize)]
struct AuthToken;

impl Modify for AuthToken {
    fn modify(&self, openapi: &mut openapi::OpenApi) {
        if let Some(schema) = openapi.components.as_mut() {
            schema.add_security_scheme(
                "jwt_token",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use utoipa::OpenApi;

    #[test]
    fn the_document_builds_and_lists_the_v012_endpoints() {
        let doc = serde_json::to_value(ApiDoc::openapi()).expect("serializable document");
        let paths = doc["paths"].as_object().expect("paths");
        for path in [
            "/api/v1/auth/login/2fa",
            "/api/v1/auth/oauth/google",
            "/api/v1/auth/password/forgot",
            "/api/v1/users/me/2fa/enable",
            "/api/v1/users/me/communication",
            "/api/v1/public/plans",
            "/api/v1/billing/me",
            "/api/v1/admin/announcements/{id}/publish",
            "/api/v1/admin/release-notes",
            "/api/v1/admin/moderation/flags/{id}/resolve",
            "/api/v1/status/details",
            "/api/v1/tours/{id}",
            "/api/v1/trash/{type}/{id}/restore",
            "/api/v1/users/me/pins",
            "/api/v1/songs/import/chordpro",
            "/api/v1/songs/{id}/export/pdf",
            "/api/v1/bands/{id}/suggestions/{sid}/vote",
            "/api/v1/bands/{id}/notes/{nid}",
            "/api/v1/bands/{id}/repertoire",
        ] {
            assert!(paths.contains_key(path), "{path} is documented");
        }
        let schemas = doc["components"]["schemas"].as_object().expect("schemas");
        for schema in [
            "BillingMe",
            "ModerationFlag",
            "UserAnnouncement",
            "LoginOutcome",
            "Tour",
            "TrashItem",
            "Suggestion",
            "PublicSong",
        ] {
            assert!(schemas.contains_key(schema), "{schema} is registered");
        }
    }
}
